//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int IdOperation { get; set; }
        public string Concept { get; set; }
        public decimal Value { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public int IdCategory { get; set; }
        public int IdUser { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
